In [28]:
# Python Math module
# print(" DIR - Math ",dir(math))
import math  
print(" Sqrt of 9 : ",math.sqrt( 9 ))  
#n=int(input(" Enter a Number : "))  
print(" Factorial Value : ",math.factorial(6)) 
print(" pow(5,3) : ",math.pow(5, 3))
print(" ceil(5.9) : ",math.ceil(5.9))
print(" floor(5.9) : ",math.floor(5.9))
print(" fabs(-4.7) : ",math.fabs(-4.7))
print(" exp(5.2) : ",math.exp(5.2))
print(" dist(2,7) : ",math.dist([2],[7]))
print(" log(10) : ",math.log(10))

# Constants in Math Module
print(" =================== ")
print(" pi value : ",math.pi)
print(" Euler's Number : ",math.e)
print(" tau value : ",math.tau)
print(" Infinity value : ",math.inf )
print(" Not a Number : ",math.nan )

# Calculating Sine, Cosine, and Tangent
print(" =================== ")
print(" sin(30) : ",math.sin((30*math.pi)/180))
print(" cos(45) : ",math.cos((45*math.pi)/180))
print(" tan(60) : ",math.tan((60*math.pi)/180))
print(" asin(30) : ",math.asin((30*math.pi)/180))
print(" acos(45) : ",math.acos((45*math.pi)/180))
print(" atan(60) : ",math.atan((60*math.pi)/180))
print(" =================== ")



 Sqrt of 9 :  3.0
 Factorial Value :  720
 pow(5,3) :  125.0
 ceil(5.9) :  6
 floor(5.9) :  5
 fabs(-4.7) :  4.7
 exp(5.2) :  181.27224187515122
 dist(2,7) :  5.0
 log(10) :  2.302585092994046
 pi value :  3.141592653589793
 Euler's Number :  2.718281828459045
 tau value :  6.283185307179586
 Infinity value :  inf
 Not a Number :  nan
 sin(30) :  0.49999999999999994
 cos(45) :  0.7071067811865476
 tan(60) :  1.7320508075688767
 asin(30) :  0.5510695830994463
 acos(45) :  0.6674572160283838
 atan(60) :  0.808448792630022


In [35]:
import statistics
#Statistics Function
print(" median : ",statistics.median([8, 10, 12, 14, 16, 18]))
print(" mean : ",statistics.mean([2, 4, 6, 8, 10, 12, 14]))
print(" mode : ",statistics.mode([20, 4, 16, 8, 10, 12, 18, 16]))
print(" median_low : ",statistics.median_low([8, 10, 12, 14, 16, 18]))
print(" median_high : ",statistics.median_high([8, 10, 12, 14, 16, 18]))
print(" median_grouped : ",statistics.median_grouped([1, 2, 3, 4], 3))
print(" harmonic_mean : ",statistics.mean([2, 4, 6, 8, 10, 12, 14]))
print(" pstdev : ",statistics.pstdev([1, 30, 50, 100]))
print(" stdev : ",statistics.stdev([1, 30, 50, 100]))
print(" variance : ",statistics.pvariance([1, 30, 50, 100]))

sample = [10, 25, 50 , 80, 100]
print(" Median : ",statistics.median([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]))
print(" Mean : ",statistics.mean([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]))
print(" Mod ",statistics.mode([20, 4, 6, 8, 10, 6, 12, 4, 6, 18, 20]))
print(" Standard Deviation : ",statistics.stdev(sample))
print(" Standard Deviation : ",statistics.pstdev(sample))
print(" Low Median : ",statistics.median_low(sample)) 
print(" High Median : ",statistics.median_high(sample))
print(" harmonic mean : ",statistics.harmonic_mean(sample))
print(" Median Groups : ",statistics.median_grouped([1, 2, 3, 4], 5))
print(" Variance : ",statistics.variance([1, 2, 3, 4], 5))


 # print(" DIR - Statistics ",dir(statistics))

 median :  13.0
 mean :  8
 mode :  16
 median_low :  12
 median_high :  14
 median_grouped :  1.5
 harmonic_mean :  8
 pstdev :  36.09276243237694
 stdev :  41.67633221226007
 variance :  1302.6875
 Median :  11.0
 Mean :  11
 Mod  6
 Standard Deviation :  37.3496987939662
 Standard Deviation :  33.406586176980134
 Low Median :  50
 High Median :  50
 harmonic mean :  27.397260273972602
 Median Groups :  0.5
 Variance :  10


In [46]:
import random
print(" Random Value : ",random.random())
print(" Radint Value : ",random.randint(1, 500))
num=random.random()
print(num)
num=random.randint(1,500)
print(num)
num = random.randrange(1, 10)
print(num)
num = random.randrange(1, 10, 2)
print(num)

random_s = random.choice('Random Module') #a string  
print( random_s )  
random_l = random.choice([23, 54, 765, 23, 45, 45]) #a list  
print( random_l )  
random_s = random.choice((12, 64, 23, 54, 34)) #a set  
print( random_s )  

list1 = [34, 23, 65, 86, 23, 43]    
random.shuffle( list1 )    
print( list1 )    
random.shuffle( list1 )    
print( list1 )    


 Random Value :  0.09213685107715974
 Radint Value :  111
0.4700308554361262
35
4
3
o
54
34
[23, 86, 34, 65, 43, 23]
[43, 65, 23, 23, 86, 34]


In [48]:
import random    
print(" Random Value : ",random.random())
print(" Random Integer Value : ",random.randint(1, 500))
print(" Random Range Value : ",random.randrange(1, 10))
print(" Random Range Value : ",random.randrange(1, 10,2))
print(" Choice Value : ",random.choice([12, 64, 23, 54, 34]))
mylist = [34, 23, 65, 86, 23, 43]    
random.shuffle(mylist)    
print(" Shuffle Values : ",mylist)   


 Random Value :  0.3287082088622667
 Random Integer Value :  410
 Random Range Value :  3
 Random Range Value :  3
 Choice Value :  12
 Shuffle Values :  [34, 65, 86, 43, 23, 23]


In [8]:
# python request method
import requests
#print(" DIR - Requests ",dir(requests))

x = requests.get("https://sathyatech.com/class-room-schedules/")
print(x.status_code)
print(x.headers)
#print(x.text)



404
{'Date': 'Sat, 10 May 2025 04:28:41 GMT', 'Server': 'Apache', 'Expires': 'Wed, 11 Jan 1984 05:00:00 GMT', 'Cache-Control': 'no-cache, must-revalidate, max-age=0, no-store, private', 'Link': '<https://sathyatech.com/wp-json/>; rel="https://api.w.org/"', 'Upgrade': 'h2', 'Connection': 'Upgrade, Keep-Alive', 'Keep-Alive': 'timeout=5, max=100', 'Content-Type': 'text/html; charset=UTF-8'}


In [14]:
# Python String Functions
text = 'Sathya Tech, HELLO world!'

# original string never changes
print("\nOriginal String",text)

# string to upper case
print(text.upper())

# string to lower case
print(text.lower())

# upper case and rest to lower case 
print(text.title())

# upper case character to lowercase and viceversa
print(text.swapcase())

# convert the first character of a string to uppercase
print(text.capitalize())

txt = "Hello9"
x = txt.isalnum()
print(x)
x = txt.isalpha()
print(x)
x = txt.isdecimal()
print(x)
x = txt.isascii()
print(x)
x = txt.isidentifier()
print(x)
txt = "Hello world"
x = txt.isidentifier()
print(x)


Original String Sathya Tech, HELLO world!
SATHYA TECH, HELLO WORLD!
sathya tech, hello world!
Sathya Tech, Hello World!
sATHYA tECH, hello WORLD!
Sathya tech, hello world!
True
False
False
True
True
False


In [15]:
import string

# string module constants
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.hexdigits)
print(string.whitespace)  # ' \t\n\r\x0b\x0c'
print(string.punctuation)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
0123456789abcdefABCDEF
 	

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [21]:
import string
from string import Formatter
from string import Template

s = "  welcome TO  \n\n SATHYA TECH"
print(string.capwords(s))

formatter = Formatter()
print(formatter.format('{website}', website='SathyaTech'))
print(formatter.format('{} {website}', 'Welcome to', website='SathyaTech'))

# format() behaves in similar manner
print('{} {website}'.format('Welcome to', website='SathyaTech'))


t = Template('$name is the $title of $company')
s = t.substitute(name='Guido van rossum', title='Founder', company='Python')
print(s)

Welcome To Sathya Tech
SathyaTech
Welcome to SathyaTech
Welcome to SathyaTech
Guido van rossum is the Founder of Python


In [22]:
# Python String Slicing
s = "SathyTech, Python"

# Retrieves characters from index 1 to 3
print(s[1:4])  

# Retrieves characters from beginning to index 2
print(s[:3])   

# Retrieves characters from index 3 to the end
print(s[3:])   

# Reverse a string
print(s[::-1])



ath
Sat
hyTech, Python
nohtyP ,hceTyhtaS


In [25]:
s = "hello Sathya"

print(" String Length : ",len(s))
# Updating by creating a new string
s1 = "H" + s[1:]
s2 = s.replace("Sathya", "Python")
print(s1)
print(s2)

print(s.upper())
print(s.lower())

name = "Sathya"
age = 22
print(f"Name: {name}, Age: {age}")


 String Length :  12
Hello Sathya
hello Python
HELLO SATHYA
hello sathya
Name: Sathya, Age: 22


In [8]:
# list vs Numpy Array
import numpy as np
#print(" DIR - NumPy: ",dir(numpy))
arr = np.array([1, 2, 3, 4, 5])
print(" Type : ",type(arr))
print(" Values : ",arr)
print(" ============= ")
lst = [1,2,3,4,5]
print(" Type : ",type(lst))
print(" Values : ",lst)



 Type :  <class 'numpy.ndarray'>
 Values :  [1 2 3 4 5]
 Type :  <class 'list'>
 Values :  [1, 2, 3, 4, 5]


In [16]:
# Dimensions in Arrays
import numpy as np

print(" ..... 0-D Arrays ..... ")
arr = np.array(42)
print(arr.ndim)
print(arr)

print("\n  ..... 1-D Arrays  .....")
arr = np.array([1, 2, 3, 4, 5])
print(arr.ndim)
print(arr)

print("\n ..... 2-D Arrya  .....")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr)

print("\n ..... 3-D Arrya  .....")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[9, 7, 8], [0, 2, 4]]])
print(arr.ndim)
print(arr)



 ..... 0-D Arrays ..... 
0
42

  ..... 1-D Arrays  .....
1
[1 2 3 4 5]

 ..... 2-D Arrya  .....
2
[[1 2 3]
 [4 5 6]]

 ..... 3-D Arrya  .....
3
[[[1 2 3]
  [4 5 6]]

 [[9 7 8]
  [0 2 4]]]


In [17]:
# Multi Dim. arrya
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [21]:
# Numpy Array Indexing
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])



1
7
2nd element on 1st row:  2
6


In [23]:
# Matrix Multiplication using NumPy Arrays
import numpy as np

# creating two matrices
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print("Matrix-1 :")
print(p)
print("Matrix-2 :")
print(q)

# computing product
result = np.dot(p, q)

# printing the result
print("The matrix multiplication is :")
print(result)


Matrix-1 :
[[1, 2], [2, 3]]
Matrix-2 :
[[4, 5], [6, 7]]
The matrix multiplication is :
[[16 19]
 [26 31]]


In [8]:
# Numpy Array Indexing and Slicing
import numpy as np

# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

# Slicing arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])

# Negative Slicing
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])


Last element from 2nd dim:  10
[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [18]:
#NumPy Data Types
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr.dtype)

# arr = np.array(['a', '2', '3'], dtype='i')  ==> Value Error

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(arr.dtype)
print(newarr.dtype)

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)


int64
<U6
|S1
int32
float64
int32
[ True False  True]
bool


In [21]:
# VIEW  and COPY Functions
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr.copy()
arr[0] = 42

print(" Original Array : ",arr)
print(" View : ",x)
print(" Copy : ",y)



 Original Array :  [42  2  3  4  5]
 View :  [42  2  3  4  5]
 Copy :  [1 2 3 4 5]


In [26]:
# Get the Shape of an Array
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr.reshape(3, 2)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)



(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [32]:
# Iterating Arrays
import numpy as np

arr = np.array([1, 2, 3])
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
      
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)
    


1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [37]:
# nditer() interation

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)


arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
    
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)
    


1
2
3
4
5
6
7
8
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
1
3
5
7
(0,) 1
(1,) 2
(2,) 3


In [8]:
#NumPy Joining Array
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)





[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
# Joining Arrays Using Stack Functions
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

#Stacking Along Rows
arr = np.hstack((arr1, arr2))
print(arr)

#Stacking Along Columns
arr = np.vstack((arr1, arr2))
print(arr)



[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [18]:
#NumPy Splitting Array
import numpy as np

#Splitting 1-D Arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

newarr = np.array_split(arr, 4)
print(newarr)

#Splitting 2-D Arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [20]:
# NumPy Searching Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)



(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)


In [24]:
# Search Sorted
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

x = np.searchsorted(arr, 7, side='right')
print(x)

# Sorting Arrays
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))



1
2
[0 1 2 3]
[[2 3 4]
 [0 1 5]]


In [26]:
#NumPy Filter Array
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

#Create a Filter Array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[41 43]
[False, True, False, True, False, True, False]
[2 4 6]


In [41]:
# Random values
from numpy import random

# Random integer
x = random.randint(100)
print(x)

# Random float
x = random.rand()
print(x)

# Generate Random Array
x=random.randint(100, size=(5))
print(x)


#choice function
x = random.choice([3, 5, 7, 9])
print(x)

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)


30
0.9997431146162558
[94 29 76 49 23]
7
[3 5 5 5 5 7 5 7 5 5 7 7 7 7 7 7 7 3 5 7 7 7 5 7 7 5 7 7 5 7 7 7 5 7 7 5 5
 7 7 5 7 5 7 7 7 5 5 5 7 7 7 7 7 7 3 7 5 5 7 5 7 5 5 5 7 7 7 7 3 7 7 5 7 7
 3 3 5 7 3 5 7 5 7 5 7 5 7 7 7 5 5 3 7 7 7 7 5 5 7 5]


In [10]:
import numpy as np
from numpy import random

# Random Distribution
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)
print(" ---------------")
# Random Permutations
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)
print(" ---------------")
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))



[[7 7 7 7 5]
 [5 7 3 5 3]
 [7 3 7 5 7]]
 ---------------
[3 1 5 2 4]
 ---------------
[5 4 3 2 1]
